import type { Metadata } from "next";

import "./globals.css";
import NavMenu, { ThemeProvider } from "@/components/navigation-menu";
import "@fontsource/russo-one";
import Footer from "@/components/sections/footer-section";
import ProgressBarWrapper from "@/components/progress-bar";

export const metadata: Metadata = {
  title: "LIYO Trading LLC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-russo antialiased `}>
        <ThemeProvider>
          <ProgressBarWrapper>
            <NavMenu />
            {children}
            <Footer />
          </ProgressBarWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
